services:
    db:
        image: postgres
        ports:
            - "5433:5433"
        environment:
            - POSTGRES_PASSWORD=afx
            - POSTGRES_USER=afx
            - POSTGRES_DB=afx
            - PGPORT=5433
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
