services:
    db:
        image: postgres
        ports:
            - "5433:5432"
        environment:
            - POSTGRES_PASSWORD=
            - POSTGRES_USER=afx
            - POSTGRES_DB=afx
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
