version: '3'

services:
    afx-db:
        image: docker.io/bitnami/postgresql:15
        ports:
            - '5432:5432'
        volumes:
            - 'pgdata:/bitnami/postgresql'
        environment:
            - POSTGRESQL_USERNAME=root
            - POSTGRESQL_PASSWORD=root
            - POSTGRESQL_DATABASE=afx
            - POSTGRESQL_PORT_NUMBER=5432
volumes:
    pgdata:
        driver: local
